In [123]:
your_file = open('dsdv25nodes1pause.txt')

In [124]:
flow = your_file.readlines()
flow

['Flow 1 (10.1.1.24 -> 10.1.1.3  Port: 49153 -> 9 protocol: 17)\n',
 'Tx Packets: 44  Rx Packets: 6  Tx Bytes:   45232  Rx Bytes: 6168\n',
 'Packet Loss Ratio: 86.3636 %\n',
 'mean Delay: 2.64825 ms\n',
 'Flow 2 (10.1.1.1 -> 10.1.1.5  Port: 49153 -> 9 protocol: 17)\n',
 'Tx Packets: 44  Rx Packets: 0  Tx Bytes:   45232  Rx Bytes: 0\n',
 'Packet Loss Ratio: 100 %\n',
 'mean Delay: -nan ms\n',
 'Flow 3 (10.1.1.16 -> 10.1.1.5  Port: 49153 -> 9 protocol: 17)\n',
 'Tx Packets: 44  Rx Packets: 2  Tx Bytes:   45232  Rx Bytes: 2056\n',
 'Packet Loss Ratio: 95.4545 %\n',
 'mean Delay: 271.965 ms\n',
 'Flow 4 (10.1.1.7 -> 10.1.1.3  Port: 49153 -> 9 protocol: 17)\n',
 'Tx Packets: 44  Rx Packets: 8  Tx Bytes:   45232  Rx Bytes: 8224\n',
 'Packet Loss Ratio: 81.8182 %\n',
 'mean Delay: 21.7098 ms\n',
 'Flow 5 (10.1.1.18 -> 10.1.1.3  Port: 49153 -> 9 protocol: 17)\n',
 'Tx Packets: 44  Rx Packets: 0  Tx Bytes:   45232  Rx Bytes: 0\n',
 'Packet Loss Ratio: 100 %\n',
 'mean Delay: -nan ms\n',
 'Flow 

In [125]:
len(flow)

482

In [126]:
#mean delay
j=0
m3 = []
for i in range(3, 482, 4): #range changes when changing the conditions for DSDV and AODV (number of nodes, pause time)
    m1 = flow[i].split()
    m2 = m1[2:3]
    #print(m2)
    m3.insert(j, m2)
    j+=1
print(m3, "\n")

#packets
q=0
p3 = []
for w in range(1, 479, 4): 
    p1 = flow[w].split()
    p2 = p1[5:6]
    p3.insert(q, p2)
    q+=1
print(p3, "\n")

[['2.64825'], ['-nan'], ['271.965'], ['21.7098'], ['-nan'], ['-nan'], ['-nan'], ['131.678'], ['114.359'], ['5.22305'], ['34.5561'], ['17.6007'], ['6.01675'], ['17.6428'], ['539.166'], ['54.7529'], ['408.454'], ['51.0617'], ['14.7174'], ['207.509'], ['358.392'], ['8.97683'], ['141.067'], ['1.87406'], ['5.58517'], ['7.07509'], ['63.7265'], ['1.88866'], ['69.8263'], ['20.3359'], ['131.773'], ['6.08105'], ['14.1115'], ['-nan'], ['680.659'], ['49.0675'], ['27.784'], ['739.154'], ['46.4711'], ['2343'], ['-nan'], ['171.917'], ['-nan'], ['131.743'], ['-nan'], ['151.482'], ['4.09987'], ['-nan'], ['12.4733'], ['8.09376'], ['50.8663'], ['16.1725'], ['14.4936'], ['604.827'], ['191.686'], ['12.3918'], ['3.056'], ['4.80468'], ['105.76'], ['15.2021'], ['10.7259'], ['263.042'], ['8.03542'], ['5.04082'], ['520.651'], ['-nan'], ['-nan'], ['459.834'], ['-nan'], ['14.3494'], ['106.133'], ['2.83886'], ['9.63035'], ['2.68632'], ['8.17224'], ['12.283'], ['4.99586'], ['13.0615'], ['3.1769'], ['64.1988'], ['10

In [127]:
import numpy as np

In [128]:
b=np.array(p3)
b2 = [list(map(float, x)) for x in b]

In [129]:
a=np.array(m3)
a2 = [list(map(float, x)) for x in a]
a2=np.array(a2)

In [130]:
c = a2*b2
c2 = np.multiply(a2, b2)

In [140]:
c3 = [list(map(float, x)) for x in c2]
c3 = np.array(c3)
c3[1]=0
c3[4]=0
c3[5]=0
c3[6]=0
c3[33]=0
c3[40]=0
c3[42]=0
c3[44]=0
c3[47]=0
c3[65]=0
c3[66]=0
c3[68]=0
c3[82]=0
c3[92]=0
c3[93]=0
c3[105]=0
c3[113]=0
c3[116]=0
c3[118]=0
c3

array([[15.89],
       [0.00],
       [543.93],
       [173.68],
       [0.00],
       [0.00],
       [0.00],
       [790.07],
       [1029.23],
       [20.89],
       [311.00],
       [105.60],
       [42.12],
       [370.50],
       [10244.15],
       [547.53],
       [3267.63],
       [510.62],
       [191.33],
       [1037.54],
       [1075.18],
       [8.98],
       [3103.47],
       [7.50],
       [22.34],
       [141.50],
       [1019.62],
       [17.00],
       [418.96],
       [183.02],
       [263.55],
       [36.49],
       [211.67],
       [0.00],
       [1361.32],
       [736.01],
       [138.92],
       [7391.54],
       [185.88],
       [11715.00],
       [0.00],
       [1203.42],
       [0.00],
       [1053.94],
       [0.00],
       [1060.37],
       [12.30],
       [0.00],
       [99.79],
       [64.75],
       [101.73],
       [258.76],
       [130.44],
       [9072.41],
       [1916.86],
       [74.35],
       [51.95],
       [57.66],
       [846.08],
       [30.40]

In [141]:
float_formatter = lambda x: "%.2f" % x
float_formatter(1.6556848e+02)
np.set_printoptions(formatter={'float_kind':float_formatter})

In [142]:
s=0
i=0
for i in range(0, 120, 1):
    temp = c3[i]
    s+=temp
s

array([132658.69])

In [143]:
p3= [list(map(float, x)) for x in p3]
p4 = np.array(p3)
tpackets =0
for i in range(0, 120, 1):
    temp = p4[i]
    tpackets+=temp
tpackets

array([898.00])

In [144]:
totaldelay = s/tpackets

In [145]:
totaldelay

array([147.73])